// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB0L6U5IBVysWs9lo5l6CGlEXCkLDDknU',
    appId: '1:199949111542:web:d56250684f0c5fa08b5cd7',
    messagingSenderId: '199949111542',
    projectId: 'gleeworld-8fea8',
    authDomain: 'gleeworld-8fea8.firebaseapp.com',
    storageBucket: 'gleeworld-8fea8.appspot.com',
    measurementId: 'G-0G1671XLK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsfQkR3_8XmUFQ8pu45gMY9EjzAnQ35PY',
    appId: '1:199949111542:android:87b8ee11b8edd36f8b5cd7',
    messagingSenderId: '199949111542',
    projectId: 'gleeworld-8fea8',
    storageBucket: 'gleeworld-8fea8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCSMmtMZ2DHqwC8UQ6DXIRy1WZe32HD7k',
    appId: '1:199949111542:ios:2408fb3dea8061a98b5cd7',
    messagingSenderId: '199949111542',
    projectId: 'gleeworld-8fea8',
    storageBucket: 'gleeworld-8fea8.appspot.com',
    iosClientId: '199949111542-4sji99d653mn93enpbovbu72mvf0o0ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.gleeworld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCSMmtMZ2DHqwC8UQ6DXIRy1WZe32HD7k',
    appId: '1:199949111542:ios:2408fb3dea8061a98b5cd7',
    messagingSenderId: '199949111542',
    projectId: 'gleeworld-8fea8',
    storageBucket: 'gleeworld-8fea8.appspot.com',
    iosClientId: '199949111542-4sji99d653mn93enpbovbu72mvf0o0ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.gleeworld',
  );
}
